### ISSUE TITLE
AsyncAPI Applications Relations Finder

### ISSUE THREAD

**Issue by derberg** [asyncapi/cupid#1]
#### Reason/Context
Would be awesome to build a library that as the input gets an array of AsyncAPI documents and analyzes them to get information about Applications described by those files:
- If they subscribe or publish to the same channels
- If one subscribes to a channel that the other one publishes to
- If there are apps that are subscribed to channels that no one publishes too

As an output, we should get a format that can be used to generate a diagram of relations between applications with additional metadata information about them (message, schemas).
 
 
Use case:

Visualization of the architecture and understanding what happens with the system if one of the puzzles is removed.
Later on, we could use this library in AsyncAPI CLI and also the AsyncAPI Studio.

Required knowledge:
There is no need to have any experience in event-driven architecture. You do not even need to know AsyncAPI spec too much. It is a pure coding task where you will need to find matching patterns between different documents and return this information. This should be an independent library that can be later reused in AsyncAPI CLI or AsyncAPI Studio, or by others in their tools.

#### Description
- you do not have to implement any reading of AsyncAPI files from disk or URL or anything like this. It is a library and its API should accept an array of AsyncAPI documents and these can be already after being parsed by https://github.com/asyncapi/parser-js/
- biggest unknow is the output, what would be the best format to choose here as an output. Should it follow syntax from [mermaid](https://mermaid-js.github.io/mermaid/#/) or maybe we need something custom? I think it would be better to first try to "manually" try to get 2 asyncapi docs, identify relations between them and then model the output "manually" to get an idea how it should be structured, maybe we need pure uml output? 🤷🏼

**Comment by derberg** [comment]
@arjungarg07 repo ready and as you can see, the initial issue is also transformed

**Comment by arjungarg07** [comment]
@derberg Thanks, will soon be opening issues for further discussions 😃

**Comment by arjungarg07** [comment]
Some discussed points:

- Would keep `Map Object` as a default output and would be configuring it to obtain output following mermaid syntax.
- Providing documentation for the developers as a walkthrough to integrate more custom formats in this library.

**Comment by arjungarg07** [comment]
> * it should show that App A has a link with App B through some message, but the relation goes through a given server

@derberg Since the Apps relation goes through a given server/broker, do we have to consider servers in production or development?

**Comment by arjungarg07** [comment]
imho this would be the custom format considering the servers/brokers too.

<img width="486" alt="Screenshot 2021-06-03 at 3 31 20 PM" src="https://user-images.githubusercontent.com/53009722/120626908-c1ba4480-c480-11eb-945c-9d6acdb6fcae.png">

**Comment by magicmatatjahu** [comment]
@arjungarg07 Hello! At the moment we cannot define in spec which server expose some channels, but currently we have PR for that https://github.com/asyncapi/spec/pull/531 so for your question: you should consider all servers, which will be logical, it means: the application A can be hosted by 2 servers then you are considering 2 servers through which application B can communicate.

**Comment by derberg** [comment]
cool tool to consider https://reactflow.dev/
I admit I have not much knowledge about it, but assume that whatever is used to render flows, probably accepts some specific format, and this is the format that could be an output here

**Comment by arjungarg07** [comment]
@magicmatatjahu Thanks for clearing it out.

So we would distinguish relations between files on 3 levels.
`1st level`: server URL 
`2nd level`: server protocol
`3rd level`: channels to which services subscribed or publishing 

Please correct me if i am wrong 🤔 



> cool tool to consider https://reactflow.dev/

@derberg yeah! i checked it out yesterday and it's super cool, would love to experiment with it but first focussing on MVP 😄

**Comment by derberg** [comment]
> but first focussing on MVP

👏🏼 

> We could club 1st and 2nd levels too

same URL with different protocols would be super unusual so you can definitely assume this is always referring to the same server

**Comment by pcornelissen** [comment]
> @arjungarg07 Hello! At the moment we cannot define in spec which server exposes some channels, but currently we have PR for that [asyncapi/spec#531](https://github.com/asyncapi/spec/pull/531) so for your question: you should consider all servers, which will be logical, it means: the application A can be hosted by 2 servers then you are considering 2 servers through which application B can communicate.

I'd like to throw into the ring that structurewise it doesn't really matter is a service is running in 1, 2 or 200 instances, it shouldn't appear with a cardinality of 200 in the flow. The main point of the message approach is that you don't care on the sender side how many workers/consumers there are. It may be an important fact for the consumer to be for example single instanced, or it is stateful, but that has IMHO nothing to do with the message flow documentation.

**Comment by magicmatatjahu** [comment]
@pcornelissen What for your insights :) I almost agree with you, but there is some situation when pinned channel only for particular server can change the rest of flow. We can use the relationship (as a user/client) to check which flow will be "created" when for example I as a user/client will send message to create a new order in e-shop. Sending the order to this same channel, but in two different server can change flow. This situation is rare, but still possible. Of course, we should in first implementation go with simple solution which will cover almost cases, and then go with more complex and rare.

If we don't understand each other, it may be because I look at the current problem (app relationship) from the perspective of the user/dev who wants to send a message to a given channel and know what operations will be performed after sending the message/event, such as creating an order, adding loyalty points etc. on the example of an e-shop.

**Comment by magicmatatjahu** [comment]
@arjungarg07 Please don't focus on first weeks on output shape (also using shape of ReactFlow isn't a good idea, we should be agnostic here). We can change it later, because currently most important part is making, as you wrote, some MVP :)

**Comment by arjungarg07** [comment]
> same URL with different protocols would be super unusual so you can definitely assume this is always referring to the same server

Yeah! but I would like to play it safe and not make any assumptions😅

**Comment by arjungarg07** [comment]
@magicmatatjahu I ran the script for on [Alvaro's flight service](https://github.com/amadeus4dev/amadeus-async-flight-status) with a slight change of adding one more server in one of the spec.
Generating default output as:
``` 
Map(2) {
  'mqtt://localhost:1883,mqtt' => Map(2) {
    'flight/update' => {
      sub: [ 'Flight Monitor Service' ],
      pub: [ 'Flight Notifier Service' ]
    },
    'flight/queue' => {
      sub: [ 'Flight Subscriber Service' ],
      pub: [ 'Flight Notifier Service', 'Flight Monitor Service' ]
    }
  },
  'mqtt://163.124.11,mqtt' => Map(2) {
    'flight/update' => { sub: [ 'Flight Monitor Service' ], pub: [] },
    'flight/queue' => { sub: [], pub: [ 'Flight Monitor Service' ] }
  }
}

```
So the mermaid diagram of this output should be like this:

<img width="682" alt="Screenshot 2021-06-08 at 6 04 41 PM" src="https://user-images.githubusercontent.com/53009722/121185739-016b9c80-c884-11eb-911f-f746a52e1acd.png">

Any feedbacks are much appreciated.

**Comment by magicmatatjahu** [comment]
@arjungarg07 I love it! Really :) As I see everything is good, 'publish' operation go to channel, from channel you link to service/app's 'subscribe' operation. At the moment is good, but honestly it's a hard to understand in first look what is connecting to what, I mean, you should look on diagram and see that you can publish something to (eg) FlightNotifierService when you will publish to `flight/update` channel and etc. It's not a problem of your code, but probably with our "description" of publish/subscribe in spec, but overall, great job! :) What do you want to do next?

**Comment by arjungarg07** [comment]
> but honestly it's a hard to understand in first look what is connecting to what

Yup! I mean the whole thing is to visualize the relations and the first look at this image feels so complex.

> What do you want to do next?
will have the script ready for generating mermaid diagrams syntax asap 🚀

**Comment by arjungarg07** [comment]
Do we have to add metadata information in the default syntax itself or have a separate API for it?

**Comment by magicmatatjahu** [comment]
@arjungarg07 Do you mean metadata like payload's schema of message etc? You operate on parsed spec, currently you save sub/pub only by name to array for appropriate channel name, to save metadata you can change the array to Map, so you have:

```
    'flight/update' => {
      sub: [ 'Flight Monitor Service' ],
      pub: [ 'Flight Notifier Service' ]
    },
```

but you can change it to Map<string, ChannelMetadata>

```
 'flight/update' => {
   sub => {
     'Flight Monitor Service' => Channel metadata,
     'Flight Notifier Service' => Channel metadata,
   }
 }
```

Of course you can save as `Channel metadata` whole object of appropriate channel of given app as reference :)

**Comment by arjungarg07** [comment]
> Do you mean metadata like payload's schema of message etc?

Yeah, and message and schemas too.


> About separate API we can think in the next weeks, at the moment we can add metadata by default to default output/syntax or add option to enable adding metadata, which will be by default set to `true.`

Sure. I will then update the metrics 👍🏽

**Comment by arjungarg07** [comment]
@derberg @jonaslagoni @magicmatatjahu Consider we need to get the metadata information like message and schema for each channel on this spec.

```yaml
channels:
  flight/update:
    description: |
      Provides updates from a subscribed flight
    subscribe:
      summary: Inform about the status of a subscribed flight
      message:
        $ref: '#/components/messages/flightStatus'
 flight/queue:
    description: |
      Queues a flight in order to retrieve status
    publish:
      summary: Subscribe about the status of a given flight
      message:
        $ref: '#/components/messages/flightQueue'
```
I can't find any API available in `parser-js` through which I can get the served message information on a particular channel, like 
```javascript 
const messageInfo =doc.channel('flight/update').message();
``` 
Same for schemas. Although we do have APIs `doc.allMessages()` and `doc.allMessages()` but it doesn't give info about on which channel it is being served.
Please correct me if I am missing something.

**Comment by magicmatatjahu** [comment]
@arjungarg07 Because message is in the `operation` item of channel - `publish` or `subscribe`. You must use in your case `doc.channel('flight/update').subscribe().message();` 

What about saving all channel's metadata (with description etc) as metadata - not only message - in relation?

**Comment by arjungarg07** [comment]
> Because message is in the `operation` item of channel

Ok, this I missed :) Thanks!

> What about saving all channel's metadata (with description etc) as metadata - not only message - in relation?

Actually, we didn't discuss Luksaz about what all to save in metadata coz i thought of asking it along the development phase. I would suggest to consider all channel's metadata as you said.

> EDIT: We have also corresponding `hasSubscribe()` and `hasPublish()` functions to check if given operation is available in channel. There is a full API of parser-js https://github.com/asyncapi/parser-js/blob/master/API.md

Yeah, I have been checking from here itself :)

**Comment by magicmatatjahu** [comment]
> EDIT: Also, what do we need to have payload as it is for metadata or just some specific parts of it?

Payload is a shape of (usually) json which should be sent to channel or will be subscribe from channel, so payload is a 
complete whole that cannot be divided into smaller parts :) If you think about different problem, please describe it in different way, because probably we don't understand each other :)

**Comment by arjungarg07** [comment]
Yeah, what I mean to say is that since we have great support for traversing schemas with support for circular references, when we will extract the metadata information from let's say message payload do we have to consider some specific fields from it or just include the whole payload itself like this:
```yaml
message: {
      payload: {
        type: 'object',
        '$id': 'PlayerItemPickupPayload',
        additionalProperties: false,
        properties: {
          pickupTimestamp: {
            type: 'string',
            format: 'date-time',
            description: 'The timestamp the item was picked up',
            'x-parser-schema-id': '<anonymous-schema-4>'
          }
        }
      },
      'x-parser-original-schema-format': 'application/vnd.aai.asyncapi;version=2.0.0',
      'x-parser-original-payload': {
        type: 'object',
        '$id': 'PlayerItemPickupPayload',
        additionalProperties: false,
        properties: {
          pickupTimestamp: {
            type: 'string',
            format: 'date-time',
            description: 'The timestamp the item was picked up'
          }
        }
      },
      schemaFormat: 'application/vnd.aai.asyncapi;version=2.0.0',
      'x-parser-message-parsed': true,
      'x-parser-message-name': '<anonymous-message-1>'
    }
  }

```

**Comment by magicmatatjahu** [comment]
@arjungarg07 I see your problem but you also put example on which I can describe my thinking :) 

You can treat only `payload` as metadata, but we must also know that dev can put inside message object specific information for given protocol, this same as in given server, so for me this is also very important metadata which we should show to user. Also channel can have specific protocol information in `bindings` object https://github.com/asyncapi/spec/blob/master/spec/asyncapi.md#channelBindingsObject You can have protocol info in `message`, `operation` (publish/subscribe), `channel` and `server` object. If we only consider message and it's value, someone can say that `headers` are also very important as metadata. I would like to say that whole data in a channel is very important metadata, so I think that treating whole channel as metadata would be the best option for our case, so I will remind you in which way I would like to do that:

```text
 'flight/update' => {
   sub => {
     'Flight Monitor Service' => Channel metadata,
     'Flight Notifier Service' => Channel metadata,
   }
 }
```

and then you don't focus which part of message is important, because you treat whole channel as metadata.

Also:

> Yeah, what I mean to say is that since we have great support for traversing schemas with support for circular references

No, we don't, we only handle simple circular refs :) I created issue for that https://github.com/asyncapi/parser-js/issues/293 so please have it in mind when you will use `traverse` function :)

What do you think about treating channel as metadata. It's easiest solution for our problem and will give us as many possibilities for the future.

**Comment by arjungarg07** [comment]
> No, we don't, we only handle simple circular refs :) I created issue for that [asyncapi/parser-js#293](https://github.com/asyncapi/parser-js/issues/293) so please have it in mind when you will use `traverse` function :)

Yeah, I just tried to iterate over it and it caused recursive stackoverflow😅



> What do you think about treating channel as metadata. It's easiest solution for our problem and will give us as many possibilities for the future

I agree with the explanation that the metadata could be important for one dev or the other and treating the channel as metadata itself would be the best possible solution 👍🏽 

```
 'flight/update' => {
   sub => {
     'Flight Monitor Service' => Channel metadata,
     'Flight Notifier Service' => Channel metadata,
   }
 }
```
Here `flight/update` is the channel and since channel's metadata would be same for every service(`Flight Monitor Service`,`Flight Notifier Service`), won't be mapping the same metadata with every service, instead we should have it like this:
```
 <channelName> => {
    sub: [ ],
    pub: [ ],
    metadata: {}
  }
```

**Comment by magicmatatjahu** [comment]
> Also, I think treating channel as metadata would have a huge ton of info to put in mermaid class diagram. How we would deal with that 🤔 

Yes, you're right about that, but partially :) For `mermaid` you can only use `payload`, `headers` and `bindings` metadata from channel, for another syntax you can only use `payload` etc. Of course, It will be "huge" data for `default` syntax, but we can read/reuse/change it for another syntaxes. You should think about it as a bridge to another syntax.

**Comment by arjungarg07** [comment]
@derberg @magicmatatjahu Check out these tools: [kroki](https://kroki.io/), [chartmage](http://chartmage.com/intro.html), [UMLGraph](https://www.spinellis.gr/umlgraph/), [yuml](https://yuml.me/diagram/scruffy/class/draw)

**Comment by derberg** [comment]
@arjungarg07 they all feel kinda the same tbh, I mean the same principle behind as in case or mermaid and plantUML. As you wrote, I think more important are tests now, and a way to test all those outputs not only from unit tests point of view but also integration tests.

And then something more beautiful........ React Flow ❤️

**Comment by arjungarg07** [comment]
I was playing a bit with React Flow 😅 and it turns out that they don't have any playground online where we can just paste the syntax and render the diagram. Then I thought of generating an HTML page but for that, I am not able to find and cdn/browser package for `react-flow-renderer` so that I can include it in that html file and code it further. I think if I could get this cdn package which I could include in HTML code, we could use puppeteer to automate opening the HTML page and taking a screenshot of the page, and save it in some file.

**Comment by derberg** [comment]
function for react flow should just generate the relations, the code responsible to show them, not entire website. This is a library, I integrate it however I want in my system, generate relations and enable in my HTML. So basically the goal is to focus on react flow code that shows relations between nodes, the HTML to present it can just be an example, part of test or a demo. Does it make sense?

**Comment by arjungarg07** [comment]
Yeah, so this is the simplest flow for ReactFlow.
``` javascript
import React from 'react';
import ReactFlow from 'react-flow-renderer';

const elements = [
  { id: '1', type: 'input', data: { label: 'Node 1' }, position: { x: 250, y: 5 } },
  // you can also pass a React Node as a label
  { id: '2', data: { label: <div>Node 2</div> }, position: { x: 100, y: 100 } },
  { id: 'e1-2', source: '1', target: '2', animated: true },
];

export default () => <ReactFlow elements={elements} />;
```
So our library function for react flow should just generate the `elements` array which could be directly passed by the user, right?

**Comment by magicmatatjahu** [comment]
@arjungarg07 Yes, elements should be the exact output from function.

**Comment by magicmatatjahu** [comment]
@arjungarg07 Important thing: If you will use inside output the VDOM nodes, like in your example `<div>Node 2</div>` you should write them with `React.createElement()` function, not as JSX, because if you use the JSX, you need then transpile your package by babel.

**Comment by magicmatatjahu** [comment]
@arjungarg07 Can we close the issue?

**Comment by derberg** [comment]
we can definitely close it, purpose of this issue was to discuss initial idea and the scope.
