### ISSUE TITLE
Overlapped edges in reactFlow

### ISSUE THREAD

**Issue by arjungarg07** [asyncapi/cupid#27]
Output Diagram for flight Service.

<img width="632" alt="Screenshot 2021-07-16 at 6 43 36 PM" src="https://user-images.githubusercontent.com/53009722/125953557-df569489-7174-4703-bb36-89a23d7d95d5.png">

for PlantUML
<img width="414" alt="Screenshot 2021-07-16 at 6 44 47 PM" src="https://user-images.githubusercontent.com/53009722/125953729-8457e7b6-0474-42c6-a9d8-a8815c495961.png">

Unfortunately, reactFlow have a problem of overlapping edges as we can see in the diagram above, when we compare it to the plantUML diagram it shows, we need the `flight/update` label shown on an edge going from `Flight Monitor Service` to the `server`. 

Solution: Implement custom edge Component: https://github.com/wbkd/react-flow/issues/819#issuecomment-758420932

**Comment by derberg** [comment]
Is this related to the output of relations discover or the example app that consumes it? How did you create the diagram that you shared in the description?

also, looking at the "advanced" nature of react flow, I think it would be nice to extend it, like make it more detailed, so when you click on the service, you see more details about it, like description and others, or when you click on the channel name label you see more details about the message sent there.

**Comment by arjungarg07** [comment]
> Is this related to the output of relations discover or the example app that consumes it? How did you create the diagram that you shared in the description?

The diagram in the description is created by passing the `elements` array that we are generating from our library.
```javascript
<ReactFlow elements={elements} />
```


> also, looking at the "advanced" nature of react flow, I think it would be nice to extend it, like make it more detailed, so when you click on the service, you see more details about it, like description and others, or when you click on the channel name label you see more details about the message sent there.

I saw the reactFlow documentation and they don't provide any such functionality, I believe you are referring to [this](https://eventbridge-atlas.netlify.app/examples/flow/), here, the functionality to click on the service and get more details about it is directly implemented in the frontend of the application.
