### ISSUE TITLE
Support flow when variables are being used in the server configuration

### ISSUE THREAD

**Issue by arjungarg07** [asyncapi/cupid#4]
We use slug to map relations with different servers described in the asyncAPI document.
```
 slug = `${credentials.url()},${credentials.protocol()}`;
```
What if user described server's url with parameters like `server/{parameter}` and define for this parameter some enum values. With the current flow we would be mapping  `server/{parameter}` as it is.

This might be a big concern and, we have to configure the flow to support this case too.

**Comment by arjungarg07** [comment]
```
servers:
- url: '{username}.gigantic-server.com:{port}/{basePath}'
  description: The production API server
  protocol: secure-mqtt
  variables:
    username:
      # note! no enum here means it is an open value
      default: demo
      description: This value is assigned by the service provider, in this example `gigantic-server.com`
    port:
      enum:
        - '8883'
        - '8884'
      default: '8883'
    basePath:
      # open meaning there is the opportunity to use special base paths as assigned by the provider, default is `v2`
      default: v2

```
We need to iterate with multiple ports: 8883, 8884 and map relations with each of them.

**Comment by derberg** [comment]
@arjungarg07 do we really need to interpret variables? I mean, if one service has asyncapi file with `{username}.gigantic-server.com:{port}`, then the other would have it too. Shouldn't we just ignore variables, and just find relations against `gigantic-server.com`

such an approach would be much easier, then we can add complexity like, check if one service has `8883` as only port and the other one `8884`. To be honest though, even if ports and username are different per server, I would still be interested to see they are related by `gigantic-server.com`

**Comment by magicmatatjahu** [comment]
@derberg We discuss this problem under one PR (probably the first one with implementation) and I agree that it's complex and not necessary at the moment - we should handle that problem in the last weeks, but also as you wrote

> ... then we can add complexity like, check if one service has 8883 as only port and the other one 8884

sometimes will be case when you have another relations (few relations) for one port and another relations for another. As I user I would like to have also information for it.

**Comment by arjungarg07** [comment]
> Shouldn't we just ignore variables and just find relations against `gigantic-server.com`

@derberg What if there are some relations specific to some ports, in that case, shouldn't we need to consider the variables? 🤔

**Comment by derberg** [comment]
long term, yup, but I see it as a kind of flag or something, be default I would ignore variables and took them into account only if explicitly requested. This could be stored as additional metadata or something that I can consume or ignore

**Comment by derberg** [comment]
Hey, do you plan to work on this one?
