### ISSUE TITLE
Refactor this redundant 'await' on a non-promise

### ISSUE THREAD

**Issue by derberg** [asyncapi/cupid#50]
More details - https://sonarcloud.io/project/issues?id=asyncapi_app-relations-discovery&issues=AXqGZiF-YcU7Bh3YkME2&open=AXqGZiF-YcU7Bh3YkME2

code from `lib/appRelationsDiscovery.js`

**Comment by iamsdas** [comment]
I'd like to work on this issue

**Comment by iamsdas** [comment]
@derberg I think it's not the `await` that is redundant. Instead it is the `validate` function which has an incorrect return type. It should return object of type `Promise<Array>` instead of `Array`

**Comment by magicmatatjahu** [comment]
@iamsdas Yes, await should stay and return type should be changed.
