### ISSUE TITLE
Remove unnecessary semicolons

### ISSUE THREAD

**Issue by derberg** [asyncapi/cupid#51]
more details:
- https://sonarcloud.io/project/issues?id=asyncapi_app-relations-discovery&issues=AXqGZiF-YcU7Bh3YkME4&open=AXqGZiF-YcU7Bh3YkME4
-  https://sonarcloud.io/project/issues?id=asyncapi_app-relations-discovery&issues=AXqGZiF-YcU7Bh3YkME3&open=AXqGZiF-YcU7Bh3YkME3

**Comment by derberg** [comment]
Awesome! Assigned

**Comment by swapnil604** [comment]
Made a pull request but giving me an error. Kindly guide me through this as I'm still a noob :p

**Comment by magicmatatjahu** [comment]
Fixed by https://github.com/asyncapi/cupid/pull/52
