### ISSUE TITLE
Suggestion for a better name of the library

### ISSUE THREAD

**Issue by arjungarg07** [asyncapi/cupid#6]
`app-relations-discovery`  is a self-descriptive name in itself, no doubt about that. But can we have a name which is short and more quick to speak. 

My proposition is more vivid and short like `web` which would then goes by the npm package `@asyncapi/web` signifying the connection between the AsyncApi docs =>  🕸️  spider web xD
Any more ideas?

**Comment by magicmatatjahu** [comment]
I think that the `web` can be associated by some people with front-end applications/libraries. My suggestion:

- `relations-discovery`
- `relations-finder`
- or shortly `discovery`

In future we can change behaviour of package to not only find relations between app, but something more :)

**Comment by arjungarg07** [comment]
> `web` can be associated by some people with front-end applications/libraries

I don't wanna give `web` away to front-end devs xD, I came up with it after a long thought😆

> In future we can change behavior of package to not only find relations between app, but something more :)

Oo! if that's the case maybe we should give this a thought after gsoc, after defining the extended behavior of it and then give a name from a big perspective :)

**Comment by derberg** [comment]
> In future we can change behavior of package to not only find relations between app, but something more :)

say what? 😄 any ideas? it was purely meant for relations discovery

`relmap`? like relations map
`mapper`?

**Comment by magicmatatjahu** [comment]
`relmap` can be, but `mapper` for me means this same as `map` - map/change one data to another

**Comment by derberg** [comment]
this is what we do here, mapping data from different files 😉

**Comment by derberg** [comment]
how about `compas` 👀

**Comment by derberg** [comment]
damn, I have a perfect name, AsyncAPI's Eve and Chan are aliens, or future human astronauts. So cosmos and galaxy.

How do we create maps of the space, of the galaxy? -> https://esahubble.org/images/potw1739a/

let us call it `hubble` 🚀 

brilliant, right?

**Comment by MikeRalphson** [comment]
Edamame - Event Driven Architecture Mapping And Management Engine.

Aardwolf - Async Api Relational Diagramming Widget Of Low Friction.

**Comment by fmvilas** [comment]
Really? Nobody thought it's "relations" finder? Cupid? Venus, the goddess of love?

I'd go for Venus or Cupid.

**Comment by MikeRalphson** [comment]
> Really? Nobody thought it's "relations" finder? Cupid? Venus, the goddess of love?
> 
> I'd go for Venus or Cupid.

Gaaydar - Graphical Async Api Diagrams And Relationships.

**Comment by smoya** [comment]
Following @derberg mood, talking about space... I like `hubble`, even though it is not in its best moments 😆 .

I'm suggesting `astrolabe`, which also has a special meaning to me. An Astrolabe is an ancient tool used for tons of things, such as discovering star positions, determine altitude and inclination, and much more. There is also a variant version for mariners.
It is not only cool but beautiful. Look at it :) 
![Iranian_Astrolabe_14](https://user-images.githubusercontent.com/1083296/122889938-899d7780-d343-11eb-9d1e-8b6281dcef28.jpeg)

Btw, I have one at home!

**Comment by derberg** [comment]
@arjungarg07 I suggest you pick up like 5 names you like the most, set up a kind of voting, and let's pick something and rename 🚀

**Comment by derberg** [comment]
lib renamed, closing
