### ISSUE TITLE
Cannot provide pre-parsed AsyncAPI documents as input

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/cupid#74]
#### Describe the bug
Based on this: https://github.com/asyncapi/cupid/issues/67#issuecomment-968961039

I tried to pre-parse my AsyncAPI documents and then give Cupid those pre-parsed documents as inputs.

#### How to Reproduce
Follow https://github.com/asyncapi/cupid/issues/67#issuecomment-968961039 example.

#### Expected behavior
By changing the validation function: https://github.com/asyncapi/cupid/blob/c9cdb3df6675d992a42ccbd9e92bd118a21a11d4/lib/utils.js#L9

To something like the following everything works:

```js
function validate(asyncApiDocs) {
  return Promise.all(asyncApiDocs.map(async doc => {
    if (typeof doc === 'object' && doc.ext && doc.ext('x-parser-spec-parsed')) {
      return doc;
    }
    return parser.parse(doc);
  }));
}
```

This is because the provided document does not have a property called `x-parser-spec-parsed` in the root object, it is hidden under `_json`, so it would be an idea to use the functions to access the extension 🙂

**Comment by arjungarg07** [comment]
Working on it.

**Comment by derberg** [comment]
it was solved, but just not properly mentioned in PR thus not closed automatically
