### ISSUE TITLE
Include Cupid as part of Async API tooling page

### ISSUE THREAD

**Issue by allantargino** [asyncapi/cupid#77]
We should add this amazing tool to https://www.asyncapi.com/docs/community/tooling :)

**Comment by derberg** [comment]
totally agree! We just need someone to add it [here](https://github.com/asyncapi/website/blob/master/pages/docs/community/tooling.md). Could you 🙏🏼

**Comment by Devansh-kajve** [comment]
Hii @allantargino can I work on this one? if you haven't started working on it already

**Comment by allantargino** [comment]
Please do @Devansh-kajve. I haven't started it yet. Thank you!

**Comment by Devansh-kajve** [comment]
@allantargino Thanks for replying, I am a beginner so can you please guide me where to start from and if possible provide me a link for a similar PR that was merged in the past

**Comment by Devansh-kajve** [comment]
@allantargino @derberg I should include it under which category? Documentation generators or code-first tools?

**Comment by derberg** [comment]
I'm not 100% sure but sounds like the best would be to put it under `Documentation Generators`

**Comment by allantargino** [comment]
I agree with @derberg :)
