### ISSUE TITLE
Imply metrics Map as class models

### ISSUE THREAD

**Issue by arjungarg07** [asyncapi/cupid#8]
Having separate classes that imply the metrics map structure could potentially improve the scope of the library because we could add multiple types of APIs.

**Comment by derberg** [comment]
can you provide more explanation, I don't fully the this one

**Comment by arjungarg07** [comment]
Currently, we have metrics as a Map but if we imply it as models just like we have in [parser-js](https://github.com/asyncapi/parser-js/tree/master/lib/models) lib, we could provide more methods for users.

cc: @jonaslagoni

**Comment by derberg** [comment]
what do you mean by `metrics`?

**Comment by arjungarg07** [comment]
> what do you mean by `metrics`?

It is the relations output 😅
https://github.com/asyncapi/app-relations-discovery/blob/e781308fdf7f535b63d61a6dbd9d2b1fea66a8a8/lib/appRelationsDiscovery.js#L28

**Comment by derberg** [comment]
oh, ok, super confusing name 😋 

anyway, long term the issue might make sense but first let us focus on MVP and shape the "metrics" Map first

**Comment by derberg** [comment]
@arjungarg07 do you plan to work on this one?

**Comment by arjungarg07** [comment]
imho we are good with the current structure and since the scope of the library is limited to only 3 types of output then it is not feasible to work on this one. What do you think?

**Comment by derberg** [comment]
yeah, I'm a fan of making improvements only if there is a use case or we simply see something really makes sense. I'm ok to close this one. We can always reopen if future if really needed
