### ISSUE TITLE
Split the functions for changing default output to another output syntax by separate functions

### ISSUE THREAD

**Issue by arjungarg07** [asyncapi/cupid#9]
At the moment user can use getRelations function and pass options which format he/she needs, but we can change this behaviour and always return default syntax and then export from package the getMermaidDiagram function, so usage of package will look like:

```javascript
const output = appRelationsDiscovery.getRelations(...asyncAPIDocs);
const mermaid = appRelationsDiscovery.getMermaidDiagram(output);
```
When we will support class models for our metrics we could have APIs which could add a subscriber or publisher to the channel to see what happens with the system if one of the puzzles is removed/added.

```javascript
const output = appRelationsDiscovery.getRelations(...asyncAPIDocs);
output.subscribe(<channelName>,<server>,<serviceName>);
const mermaid = appRelationsDiscovery.getMermaidDiagram(output);
```

**Comment by derberg** [comment]
Makes sense, adds more flexibility

**Comment by derberg** [comment]
Do I actually have to pass `output` here `appRelationsDiscovery.getMermaidDiagram(output)`. 
Once I do `appRelationsDiscovery.getRelations(...asyncAPIDocs)` the output can be stored in the class, so then I can just do `appRelationsDiscovery.getMermaidDiagram()`.

**Comment by arjungarg07** [comment]
What if the user wants to change the default output manually and then pass it to `appRelationsDiscovery.getMermaidDiagram(output).`  If it isn't the case then we can definitely have `appRelationsDiscovery.getMermaidDiagram()` after we switch to class models.

**Comment by derberg** [comment]
if argument is passed, you use the one that user passed, otherwise take the one from the object
